#!/usr/bin/env ruby
# frozen_string_literal: true

# Build the essenfont npm package: stages per-plane WOFF2s into npm/
# and emits ready-to-import CSS files.
#
# Usage:
#   bundle exec ruby scripts/build_npm_package.rb [--publish]
#
# Outputs:
#   npm/package.json
#   npm/css/all.css
#   npm/css/essenfont-bmp.css (and -smp, -sip, -tip, -ssp)
#   npm/fonts/Essenfont-BMP.woff2 (etc.)
#   npm/README.md
#
# Publish:
#   cd npm && npm publish --access public
# (CI does this automatically on tag push; the --publish flag is for
# manual releases from a maintainer machine.)

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "json"
require "fileutils"
require "pathname"

module BuildNpmPackage
  ROOT = File.expand_path("..", __dir__)
  NPM_DIR = File.join(ROOT, "npm")

  PLANES = [
    { key: :BMP, label: "Basic Multilingual Plane",            range: "U+0000-FFFF",   file: "Essenfont-BMP.woff2" },
    { key: :SMP, label: "Supplementary Multilingual Plane",    range: "U+10000-1FFFF", file: "Essenfont-SMP.woff2" },
    { key: :SIP, label: "Supplementary Ideographic Plane",     range: "U+20000-2FFFF", file: "Essenfont-SIP.woff2" },
    { key: :TIP, label: "Tertiary Ideographic Plane",          range: "U+30000-3FFFF", file: "Essenfont-TIP.woff2" },
    { key: :SSP, label: "Supplementary Special-purpose Plane", range: "U+E0000-EFFFF", file: "Essenfont-SSP.woff2" }
  ].freeze

  def self.build(version: nil, publish: false)
    version ||= detect_version
    stage_fonts
    emit_css_files
    emit_package_json(version:)
    emit_readme(version:)

    if publish
      publish!
    else
      puts "npm package staged in npm/ (run `cd npm && npm publish` to publish)"
    end
  end

  def self.detect_version
    path = File.join(ROOT, "VERSION")
    if File.exist?(path)
      File.read(path).strip
    else
      warn "warn: no VERSION file; using 0.0.0-dev. Create a VERSION file for releases."
      "0.0.0-dev"
    end
  end

  def self.stage_fonts
    FileUtils.rm_rf(File.join(NPM_DIR, "fonts"))
    FileUtils.mkdir_p(File.join(NPM_DIR, "fonts"))

    PLANES.each do |p|
      src = File.join(ROOT, p[:file])
      dst = File.join(NPM_DIR, "fonts", p[:file])
      unless File.exist?(src)
        warn "warn: #{src} missing — run `ruby scripts/build.rb --format=ttf-per-plane` + WOFF2 encode first"
        next
      end
      FileUtils.cp(src, dst)
      puts "  staged #{p[:file]} (#{File.size(dst)} bytes)"
    end
  end

  def self.emit_css_files
    css_dir = File.join(NPM_DIR, "css")
    FileUtils.rm_rf(css_dir)
    FileUtils.mkdir_p(css_dir)

    PLANES.each do |p|
      css = <<~CSS
        /* essenfont-#{p[:key].to_s.downcase}.css — #{p[:label]} (#{p[:range]}) */
        /* Auto-generated by scripts/build_npm_package.rb. Do not edit by hand. */
        @font-face {
          font-family: 'Essenfont';
          src: url('../fonts/#{p[:file]}') format('woff2');
          font-weight: 100 900;
          font-style: normal;
          font-display: swap;
          unicode-range: #{p[:range].sub('U+', '').sub('-', '-')};
        }
      CSS
      # Fix unicode-range format: input is "U+0000-FFFF" → keep as-is but normalize
      css.gsub!(/unicode-range: ([^;]+);/) { "unicode-range: U+#{p[:range].sub('U+', '')};" }
      File.write(File.join(css_dir, "essenfont-#{p[:key].to_s.downcase}.css"), css)
    end

    # all.css imports every plane
    imports = PLANES.map { |p| "@import url('./essenfont-#{p[:key].to_s.downcase}.css');" }.join("\n")
    File.write(File.join(css_dir, "all.css"),
               "/* essenfont all.css — imports all 5 plane subfonts. */\n#{imports}\n")
    puts "  wrote css/ (5 plane files + all.css)"
  end

  def self.emit_package_json(version:)
    spec = {
      name: "essenfont",
      version: version,
      description: "Universal Unicode 17 font — every assigned codepoint, real outlines.",
      main: "css/all.css",
      style: "css/all.css",
      files: %w[css fonts README.md].freeze,
      keywords: %w[font unicode unicode-17 fallback otc noto cjk tofu
                   web-font woff2 multi-script].freeze,
      license: "OFL-1.1",
      homepage: "https://essenfont.github.io",
      repository: {
        type: "git",
        url: "https://github.com/essenfont/essenfont.git"
      },
      bugs: {
        url: "https://github.com/essenfont/essenfont/issues"
      },
      publishConfig: {
        access: "public"
      }
    }
    File.write(File.join(NPM_DIR, "package.json"), JSON.pretty_generate(spec))
    puts "  wrote package.json (v#{version})"
  end

  def self.emit_readme(version:)
    readme = <<~README
      # essenfont

      _Universal Unicode 17 font — every assigned codepoint, real outlines._

      [![npm version](https://img.shields.io/npm/v/essenfont.svg)](https://www.npmjs.com/package/essenfont)
      [![license](https://img.shields.io/badge/license-OFL--1.1-success.svg)](https://openfontlicense.org)

      ## Install

      ```bash
      npm install essenfont
      ```

      ## Use

      Import the full plane set:

      ```js
      import 'essenfont/css/all.css'
      ```

      Or import a single plane (smaller bundle if you only need one):

      ```js
      import 'essenfont/css/essenfont-bmp.css'  // Latin, Greek, CJK Unified, common scripts
      import 'essenfont/css/essenfont-sip.css'  // CJK Extensions B/C/D/E/F
      ```

      Add essenfont as the last entry in your font stack so any codepoint not
      covered by your active font renders via essenfont:

      ```css
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif, 'Essenfont';
      }
      ```

      ## What's in the box

      Five WOFF2 files (one per Unicode plane) + auto-generated `@font-face`
      CSS with `unicode-range` so the browser only fetches the planes a
      visitor actually needs.

      | Plane | Range | Use case |
      |-------|-------|----------|
      | BMP   | U+0000–FFFF    | World scripts, CJK Unified, common symbols |
      | SMP   | U+10000–1FFFF  | Historical scripts, emoji, math, music |
      | SIP   | U+20000–2FFFF  | CJK Extensions B/C/D/E/F |
      | TIP   | U+30000–3FFFF  | CJK Ext C+J, Tangut, Khitan |
      | SSP   | U+E0000–EFFFF  | Language tags (rarely needed) |

      ## Coverage

      Covers every assigned Unicode 17 codepoint (~131,000 unique glyphs).
      Real vector outlines — no tofu, no bitmap placeholders.

      ## License

      OFL-1.1 for most glyphs. CJK glyphs derived from Full-Sung carry an
      additional non-commercial restriction (FSung-NC). See
      [the website](https://essenfont.github.io/license) for the full
      per-donor attribution and the FSung-NC codepoint filter.

      ## Version

      This package is v#{version}, built from
      [essenfont @ GitHub](https://github.com/essenfont/essenfont).
    README
    File.write(File.join(NPM_DIR, "README.md"), readme)
  end

  def self.publish!
    Dir.chdir(NPM_DIR) do
      warn "→ npm publish --access public"
      system("npm publish --access public") || raise("npm publish failed")
    end
  end
end

publish = ARGV.delete("--publish")
BuildNpmPackage.build(publish: publish)
