# frozen_string_literal: true

require "json"
require "fileutils"

module Essenfont
  module Release
    # NpmPackage: stages per-plane WOFF2s + CSS + package.json + README.
    #
    # The npm package is the primary distribution channel for web
    # embedding. CSS files use @font-face with unicode-range so
    # bundlers can tree-shake to only the planes a consumer needs.
    module NpmPackage
      PLANES = [
        { key: :BMP, label: "Basic Multilingual Plane",            range: "U+0000-FFFF",   file: "Essenfont-BMP.woff2" },
        { key: :SMP, label: "Supplementary Multilingual Plane",    range: "U+10000-1FFFF", file: "Essenfont-SMP.woff2" },
        { key: :SIP, label: "Supplementary Ideographic Plane",     range: "U+20000-2FFFF", file: "Essenfont-SIP.woff2" },
        { key: :TIP, label: "Tertiary Ideographic Plane",          range: "U+30000-3FFFF", file: "Essenfont-TIP.woff2" },
        { key: :SSP, label: "Supplementary Special-purpose Plane", range: "U+E0000-EFFFF", file: "Essenfont-SSP.woff2" }
      ].freeze

      module_function

      # @param out_dir [String] release output directory (WOFF2s live here)
      # @param publish [Boolean] if true, run npm publish after staging
      def build(out_dir:, publish: false)
        npm_dir = File.join(out_dir, "npm")
        FileUtils.rm_rf(npm_dir)
        fonts_dir = File.join(npm_dir, "fonts")
        css_dir = File.join(npm_dir, "css")
        FileUtils.mkdir_p([fonts_dir, css_dir])

        version = Essenfont::Otc::Version::STRING

        stage_fonts(fonts_dir, out_dir)
        emit_css_files(css_dir)
        emit_package_json(npm_dir, version)
        emit_readme(npm_dir, version)

        if publish
          Dir.chdir(npm_dir) do
            system("npm publish --provenance --access public") || raise("npm publish failed")
          end
        else
          Dir.chdir(npm_dir) { `npm pack` }
        end
        puts "  npm package: v#{version}"
      end

      def stage_fonts(fonts_dir, out_dir)
        PLANES.each do |p|
          src = File.join(out_dir, p[:file])
          next unless File.exist?(src)

          FileUtils.cp(src, File.join(fonts_dir, p[:file]))
        end
      end

      def emit_css_files(css_dir)
        PLANES.each do |p|
          css = <<~CSS
            /* essenfont-#{p[:key].to_s.downcase}.css — #{p[:label]} (#{p[:range]}) */
            /* Auto-generated by the essenfont build. Do not edit by hand. */
            @font-face {
              font-family: 'Essenfont';
              src: url('../fonts/#{p[:file]}') format('woff2');
              font-weight: 100 900;
              font-style: normal;
              font-display: swap;
              unicode-range: #{p[:range]};
            }
          CSS
          File.write(File.join(css_dir, "essenfont-#{p[:key].to_s.downcase}.css"), css)
        end

        imports = PLANES.map { |p| "@import url('./essenfont-#{p[:key].to_s.downcase}.css');" }.join("\n")
        File.write(File.join(css_dir, "all.css"),
                   "/* essenfont all.css — imports all 5 plane subfonts. */\n#{imports}\n")
      end

      def emit_package_json(npm_dir, version)
        spec = {
          name: "essenfont",
          version: version,
          description: "Universal Unicode 17 font — every assigned codepoint, real outlines.",
          main: "css/all.css",
          style: "css/all.css",
          files: %w[css fonts README.md].freeze,
          keywords: %w[font unicode unicode-17 fallback otc noto cjk tofu web-font woff2 multi-script].freeze,
          license: "OFL-1.1",
          homepage: "https://essenfont.github.io",
          repository: { type: "git", url: "https://github.com/essenfont/essenfont.git" },
          bugs: { url: "https://github.com/essenfont/essenfont/issues" },
          publishConfig: { access: "public" }
        }
        File.write(File.join(npm_dir, "package.json"), JSON.pretty_generate(spec))
      end

      def emit_readme(npm_dir, version)
        readme = <<~README
          # essenfont

          _Universal Unicode 17 font — every assigned codepoint, real outlines._

          [![npm version](https://img.shields.io/npm/v/essenfont.svg)](https://www.npmjs.com/package/essenfont)
          [![license](https://img.shields.io/badge/license-OFL--1.1-success.svg)](https://openfontlicense.org)

          ## Install

          ```bash
          npm install essenfont
          ```

          ## Use

          Import the full plane set:

          ```js
          import 'essenfont/css/all.css'
          ```

          Or import a single plane (smaller bundle if you only need one):

          ```js
          import 'essenfont/css/essenfont-bmp.css'
          import 'essenfont/css/essenfont-sip.css'
          ```

          Add essenfont as the last entry in your font stack so any codepoint not
          covered by your active font renders via essenfont:

          ```css
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif, 'Essenfont';
          }
          ```

          ## License

          OFL-1.1 for most glyphs. CJK glyphs derived from Full-Sung carry an
          additional non-commercial restriction (FSung-NC). See
          [the website](https://essenfont.github.io/license) for the full
          per-donor attribution and the FSung-NC codepoint filter.

          ## Version

          v#{version}, built from [essenfont @ GitHub](https://github.com/essenfont/essenfont).
        README
        File.write(File.join(npm_dir, "README.md"), readme)
      end
    end
  end
end
